
import React, { useState, useMemo } from 'react';
import { useData } from '../context/DataContext';
import { ExpenseCategory, Expense, SaleStatus } from '../types';
import { 
  Plus, X, Trash2, Edit2, AlertTriangle, Coins, 
  TrendingDown, Filter, Calendar, Tag, Megaphone, 
  Truck, Package, Layers, MoreHorizontal, ReceiptText
} from 'lucide-react';

const CATEGORY_STYLES: Record<string, { bg: string, text: string, icon: any }> = {
  [ExpenseCategory.MARKETING]: { bg: 'bg-blue-50', text: 'text-blue-600', icon: Megaphone },
  [ExpenseCategory.DELIVERY]: { bg: 'bg-amber-50', text: 'text-amber-600', icon: Truck },
  [ExpenseCategory.PACKAGING]: { bg: 'bg-emerald-50', text: 'text-emerald-600', icon: Package },
  [ExpenseCategory.PLATFORM_FEE]: { bg: 'bg-indigo-50', text: 'text-indigo-600', icon: Coins },
  [ExpenseCategory.SALES_LOSS]: { bg: 'bg-orange-50', text: 'text-orange-600', icon: TrendingDown },
  [ExpenseCategory.REFUND_LOSS]: { bg: 'bg-rose-50', text: 'text-rose-600', icon: AlertTriangle },
  [ExpenseCategory.OTHER]: { bg: 'bg-gray-50', text: 'text-gray-600', icon: Layers },
};

const Expenses: React.FC = () => {
  const { expenses, sales, addExpense, updateExpense, deleteExpense, settings } = useData();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [expenseToDelete, setExpenseToDelete] = useState<string | null>(null);
  const [editingExpense, setEditingExpense] = useState<Expense | null>(null);

  const [filterDate, setFilterDate] = useState(new Date().toISOString().slice(0, 7));

  const [formData, setFormData] = useState({
    category: ExpenseCategory.OTHER,
    description: '',
    amount: '',
    date: new Date().toISOString().split('T')[0]
  });

  const mergedExpenses = useMemo(() => {
    const feeExpenses = sales
      .filter(s => s.status === SaleStatus.COMPLETED && s.platformFee > 0 && s.profit >= 0)
      .map(s => ({
        id: `fee-${s.id}`,
        category: ExpenseCategory.PLATFORM_FEE,
        description: `${s.platform} Fee - ${s.productName}`,
        amount: s.platformFee,
        date: s.date,
        isAutoGenerated: true,
        sourceSaleId: s.id,
        platformFee: 0
      }));

    const lossExpenses = sales
      .filter(s => s.status === SaleStatus.COMPLETED && s.profit < 0)
      .map(s => ({
        id: `loss-${s.id}`,
        category: ExpenseCategory.SALES_LOSS,
        description: `Loss on Sale - ${s.productName} (Qty: ${s.quantity})`,
        amount: Math.abs(s.profit),
        date: s.date,
        isAutoGenerated: true,
        sourceSaleId: s.id,
        platformFee: s.platformFee
      }));

    const allItems = [...expenses, ...feeExpenses, ...lossExpenses];
    const filtered = allItems.filter(item => item.date.startsWith(filterDate));
    return filtered.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }, [expenses, sales, filterDate]);

  const categoryTotals = useMemo(() => {
    const totals: Record<string, number> = {};
    mergedExpenses.forEach(e => {
      totals[e.category] = (totals[e.category] || 0) + e.amount;
    });
    return totals;
  }, [mergedExpenses]);

  const totalFilteredAmount = useMemo(() => mergedExpenses.reduce((sum, e) => sum + e.amount, 0), [mergedExpenses]);

  const handleOpenModal = (expense?: Expense) => {
    if (expense) {
      setEditingExpense(expense);
      setFormData({
        category: expense.category,
        description: expense.description,
        amount: expense.amount.toString(),
        date: new Date(expense.date).toISOString().split('T')[0]
      });
    } else {
      setEditingExpense(null);
      setFormData({
        category: ExpenseCategory.OTHER,
        description: '',
        amount: '',
        date: new Date().toISOString().split('T')[0]
      });
    }
    setIsModalOpen(true);
  };

  const handleSave = (keepOpen: boolean = false) => {
    const payload = {
      category: formData.category,
      description: formData.description,
      amount: parseFloat(formData.amount) || 0,
      date: new Date(formData.date).toISOString()
    };

    if (editingExpense) {
      updateExpense(editingExpense.id, payload);
    } else {
      addExpense(payload);
    }

    if (keepOpen) {
      setFormData({ ...formData, description: '', amount: '' });
    } else {
      setIsModalOpen(false);
    }
  };

  const confirmDelete = () => {
    if (expenseToDelete) {
      deleteExpense(expenseToDelete);
      setExpenseToDelete(null);
    }
  };

  return (
    <div className="p-4 min-h-full pb-24 bg-gray-50/50">
      <header className="mb-6 space-y-4">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Expenses</h1>
            <p className="text-xs font-medium text-gray-500 uppercase tracking-widest">Financial Outflow</p>
          </div>
          <button 
            type="button"
            onClick={() => handleOpenModal()}
            className="bg-indigo-600 text-white p-3 rounded-2xl shadow-lg shadow-indigo-100 hover:bg-indigo-700 transition-all active:scale-95"
          >
            <Plus size={24} />
          </button>
        </div>

        {/* Total Summary Card */}
        <div className="bg-gradient-to-br from-gray-900 to-indigo-950 p-5 rounded-[2rem] text-white shadow-xl shadow-gray-200 relative overflow-hidden">
          <div className="absolute -right-4 -top-4 opacity-10">
            <ReceiptText size={120} />
          </div>
          <div className="relative z-10">
            <div className="flex justify-between items-start mb-4">
              <div className="bg-white/10 px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider backdrop-blur-md border border-white/10">
                {new Date(filterDate).toLocaleString('default', { month: 'long', year: 'numeric' })}
              </div>
              <div className="relative">
                <input 
                  type="month" 
                  value={filterDate}
                  onChange={(e) => setFilterDate(e.target.value)}
                  className="bg-white/5 border border-white/20 text-white text-[11px] font-bold rounded-xl focus:ring-indigo-500 block p-2 outline-none cursor-pointer"
                />
              </div>
            </div>
            <p className="text-xs text-indigo-200 font-medium mb-1">Total Monthly Spending</p>
            <p className="text-4xl font-black">{settings.currencySymbol}{totalFilteredAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
          </div>
        </div>

        {/* Spending Breakdown Pulse */}
        {totalFilteredAmount > 0 && (
          <div className="bg-white p-4 rounded-2xl border border-gray-100 shadow-sm">
            <h3 className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-3 flex items-center gap-2">
              <Tag size={12} /> Spending Pulse
            </h3>
            <div className="flex h-3 w-full rounded-full overflow-hidden bg-gray-100 mb-4">
              {Object.entries(categoryTotals).map(([cat, amountRaw], idx) => {
                const amount = amountRaw as number;
                const percentage = (amount / totalFilteredAmount) * 100;
                const style = CATEGORY_STYLES[cat] || CATEGORY_STYLES[ExpenseCategory.OTHER];
                return (
                  <div 
                    key={cat}
                    style={{ width: `${percentage}%` }}
                    className={`${style.bg.replace('-50', '-500')} h-full transition-all`}
                    title={`${cat}: ${percentage.toFixed(1)}%`}
                  />
                );
              })}
            </div>
            <div className="grid grid-cols-2 gap-y-2 gap-x-4">
              {Object.entries(categoryTotals).slice(0, 4).map(([cat, amountRaw]) => {
                const amount = amountRaw as number;
                const style = CATEGORY_STYLES[cat] || CATEGORY_STYLES[ExpenseCategory.OTHER];
                const Icon = style.icon;
                return (
                  <div key={cat} className="flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-full ${style.bg.replace('-50', '-500')}`} />
                    <span className="text-[10px] font-bold text-gray-500 truncate">{cat}</span>
                    <span className="text-[10px] font-black text-gray-800 ml-auto">{settings.currencySymbol}{amount.toFixed(0)}</span>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </header>

      {/* Expense List */}
      <div className="space-y-3">
         {mergedExpenses.length === 0 ? (
          <div className="text-center py-16 px-4">
            <div className="bg-white w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4 border border-dashed border-gray-200 text-gray-300">
               <ReceiptText size={40} />
            </div>
            <p className="text-sm font-bold text-gray-900">No records found</p>
            <p className="text-xs text-gray-400 mt-1">Select a different month or add a new expense.</p>
          </div>
        ) : (
          mergedExpenses.map(expense => {
            const isAuto = (expense as any).isAutoGenerated;
            const isLoss = expense.category === ExpenseCategory.SALES_LOSS;
            const style = CATEGORY_STYLES[expense.category] || CATEGORY_STYLES[ExpenseCategory.OTHER];
            const Icon = style.icon;
            
            return (
              <div key={expense.id} className="bg-white rounded-2xl shadow-sm border border-gray-100 hover:border-indigo-100 transition-all group overflow-hidden">
                <div className="p-4 flex items-center gap-4">
                  <div className={`w-12 h-12 ${style.bg} ${style.text} rounded-2xl flex items-center justify-center shrink-0 transition-transform group-hover:scale-110`}>
                    <Icon size={24} />
                  </div>
                  
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-0.5">
                      <span className={`text-[9px] font-black uppercase tracking-wider ${style.text}`}>
                        {expense.category}
                      </span>
                      <span className="text-[9px] font-bold text-gray-300 uppercase">
                        • {new Date(expense.date).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}
                      </span>
                    </div>
                    <h3 className="font-bold text-gray-800 text-sm truncate pr-2">
                      {expense.description || "Uncategorized"}
                    </h3>
                  </div>

                  <div className="text-right shrink-0">
                    <p className="text-sm font-black text-gray-900">
                      -{settings.currencySymbol}{expense.amount.toFixed(2)}
                    </p>
                    {isAuto && (
                      <span className="text-[8px] font-black uppercase text-indigo-400 bg-indigo-50 px-1.5 py-0.5 rounded-full mt-1 inline-block">
                        Auto-Deducted
                      </span>
                    )}
                  </div>
                </div>
                
                {!isAuto ? (
                  <div className="flex bg-gray-50/50 border-t border-gray-50 p-1">
                    <button 
                      type="button"
                      onClick={() => handleOpenModal(expense)}
                      className="flex-1 py-2 text-[9px] font-black uppercase text-gray-400 hover:text-indigo-600 hover:bg-indigo-50/50 rounded-xl transition-all flex items-center justify-center gap-1.5"
                    >
                      <Edit2 size={12} /> Edit Record
                    </button>
                    <div className="w-px h-4 bg-gray-200 self-center" />
                    <button 
                      type="button"
                      onClick={() => setExpenseToDelete(expense.id)}
                      className="flex-1 py-2 text-[9px] font-black uppercase text-gray-400 hover:text-red-500 hover:bg-red-50/50 rounded-xl transition-all flex items-center justify-center gap-1.5"
                    >
                      <Trash2 size={12} /> Remove
                    </button>
                  </div>
                ) : (
                  <div className="bg-gray-50/50 px-4 py-2 border-t border-gray-50 flex items-center justify-between">
                     <span className="text-[9px] font-bold text-gray-400">
                        Linked Transaction
                     </span>
                     <MoreHorizontal size={14} className="text-gray-300" />
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

       {/* Form Modal */}
       {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm">
          <div className="bg-white rounded-[2.5rem] shadow-2xl w-full max-w-sm animate-in fade-in zoom-in duration-200 overflow-hidden">
            <div className="p-6 bg-indigo-600 text-white flex justify-between items-center">
              <div>
                <h2 className="text-lg font-black tracking-tight">{editingExpense ? 'Modify' : 'New'} Expense</h2>
                <p className="text-[10px] text-indigo-100 uppercase tracking-widest font-bold">Manual Entry</p>
              </div>
              <button type="button" onClick={() => setIsModalOpen(false)} className="bg-white/10 hover:bg-white/20 p-2 rounded-2xl transition-colors">
                <X size={20} />
              </button>
            </div>
            
            <form onSubmit={(e) => { e.preventDefault(); handleSave(false); }} className="p-6 space-y-5">
               <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2 ml-1">Spending Category</label>
                  <div className="grid grid-cols-2 gap-2">
                    {Object.values(ExpenseCategory)
                      .filter(c => c !== ExpenseCategory.PLATFORM_FEE && c !== ExpenseCategory.SALES_LOSS)
                      .map(c => (
                      <button
                        key={c}
                        type="button"
                        onClick={() => setFormData({...formData, category: c as ExpenseCategory})}
                        className={`py-2 px-3 text-[10px] font-bold rounded-xl border-2 transition-all ${
                          formData.category === c 
                          ? 'border-indigo-600 bg-indigo-50 text-indigo-700' 
                          : 'border-gray-100 text-gray-400 hover:border-gray-200'
                        }`}
                      >
                        {c}
                      </button>
                    ))}
                  </div>
                </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1">Date</label>
                  <input 
                    type="date" 
                    className="w-full p-3 bg-gray-50 border-none rounded-2xl text-sm font-bold focus:ring-2 focus:ring-indigo-500 outline-none" 
                    value={formData.date} 
                    onChange={e => setFormData({...formData, date: e.target.value})} 
                  />
                </div>
                <div className="space-y-1">
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1">Amount</label>
                  <div className="relative">
                    <span className="absolute left-3 top-3.5 text-xs font-black text-gray-400">{settings.currencySymbol}</span>
                    <input 
                      required 
                      type="number" 
                      step="0.01" 
                      placeholder="0.00" 
                      className="w-full p-3 pl-8 bg-gray-50 border-none rounded-2xl text-sm font-bold focus:ring-2 focus:ring-indigo-500 outline-none" 
                      value={formData.amount} 
                      onChange={e => setFormData({...formData, amount: e.target.value})} 
                    />
                  </div>
                </div>
              </div>
              
              <div className="space-y-1">
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1">Notes / Description</label>
                <input 
                  type="text" 
                  placeholder="What was this for?" 
                  className="w-full p-3 bg-gray-50 border-none rounded-2xl text-sm font-medium focus:ring-2 focus:ring-indigo-500 outline-none" 
                  value={formData.description} 
                  onChange={e => setFormData({...formData, description: e.target.value})} 
                />
              </div>

              <div className="flex flex-col gap-3 pt-4">
                <button type="submit" className="w-full bg-indigo-600 text-white font-black py-4 rounded-3xl shadow-lg shadow-indigo-100 hover:bg-indigo-700 transition-all active:scale-[0.98]">
                  {editingExpense ? 'Update Records' : 'Save Expense'}
                </button>
                
                {!editingExpense && (
                  <button 
                    type="button" 
                    onClick={() => handleSave(true)}
                    className="w-full bg-gray-50 text-gray-500 font-black py-4 rounded-3xl hover:bg-gray-100 transition-all border border-gray-100"
                  >
                    Quick Add & New
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation */}
      {expenseToDelete && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm">
          <div className="bg-white rounded-[2.5rem] shadow-2xl w-full max-w-sm p-8 animate-in zoom-in fade-in duration-200">
            <div className="flex flex-col items-center text-center">
              <div className="w-20 h-20 bg-rose-50 rounded-full flex items-center justify-center mb-6 text-rose-500">
                <AlertTriangle size={40} />
              </div>
              <h3 className="text-xl font-black text-gray-900 tracking-tight">Erase Record?</h3>
              <p className="text-sm text-gray-500 mt-2 mb-8 leading-relaxed">This record will be permanently deleted from your logs. This cannot be undone.</p>
              
              <div className="flex gap-4 w-full">
                <button 
                  onClick={() => setExpenseToDelete(null)} 
                  className="flex-1 py-4 bg-gray-50 text-gray-700 font-black rounded-3xl hover:bg-gray-100 transition-all"
                >
                  Cancel
                </button>
                <button 
                  onClick={confirmDelete} 
                  className="flex-1 py-4 bg-rose-500 text-white font-black rounded-3xl hover:bg-rose-600 transition-all shadow-lg shadow-rose-100"
                >
                  Confirm
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Expenses;
